### ISSUE TITLE
Feature request: watch mode

### ISSUE THREAD

**Issue by leegee** [t2ym/wct-headless#10]
Not sure how this would work, but would be great if the tests re-ran when a watched file is changed -- as if reloading a page in a visible browser. Hardly hot module reload, but it would help bring the Polymer workflow into a more bearable realm.

**Comment by t2ym** [comment]
Hi @leegee, I am afraid the feature should be implemented via ['gulp-watch'](https://www.npmjs.com/package/gulp-watch) like this, while I have not verified this tiny code.

```javascript
var gulp = require("gulp");
var watch = require('gulp-watch');
var puppeteer = require('puppeteer');
var runSequence = require('run-sequence');

var browser, page;
gulp.task("load", async function() {
  browser = await puppeteer.launch({ headless: false, args: [ ], executablePath: chromePath });
  page = await browser.newPage();
  await page.goto('URL for polyserve test/ like http://localhost:8081/components/my-element/test/');
});

gulp.task("reload", async function() {
  await page.reload();
});

gulp.task("do-watch", function() {
    return watch('src/**/*', function() {
        gulp.start(['reload']);
    });
});

gulp.task('watch', (done) => {
  runSequence('load', 'do-watch', done);
});
```

**Comment by leegee** [comment]
Thanks — I thought that might have to be the case.  Polymer central really needs to focus on re-tooling...!
