### ISSUE TITLE
Add chromeOptions to specify Chrome command line options

### ISSUE THREAD

**Issue by t2ym** [t2ym/wct-headless#3]
Add chromeOptions to specify Chrome command line options, i.e., ChromeDriver's `chromeOptions.args`.
It can resolve https://github.com/t2ym/wct-headless/pull/2 with more flexibility.

### `wct.conf.json`:
```javascript
{
  "plugins": {
    "local": {
      "disabled": true
    },
    "headless": {
      "browsers": [
        "chrome"
      ],
      "chromeOptions": [
        "window-size=1920,1080",
        "headless",
        "disable-gpu"
        "no-sandbox"
      ]
    }
  }
}
```

When `"chromeOptions"` is omitted the default value is: `["start-maximized","headless","disable-gpu"]`

**Comment by karolchmist** [comment]
It works great, thanks for a super fast modification!
