### ISSUE TITLE
Deprecate wct-headless since the changes have been merged to wct-local

### ISSUE THREAD

**Issue by t2ym** [t2ym/wct-headless#9]
Deprecate `wct-headless` since the changes have been merged into the official `wct-local@2.1.0` with [this PR](https://github.com/Polymer/wct-local/pull/71)

## Notes
- I have not verified the headless support (Chrome and Firefox) in `wct-local@2.1.0`

**Comment by paladox** [comment]
I have verified that chrome headless works in wct-local. But firefox headless does not seem to work.

**Comment by eidottermihi** [comment]
Can confirm firefox headless is working with `wct-local@2.1.0` and firefox 58.

**Comment by t2ym** [comment]
Performed `npm deprecate`
